name: Daily Commit Job

on:
  schedule:
    - cron: '25 4 * * *'  # Runs daily at 4:25 AM UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update daily_status.txt (22f3000940@ds.study.iitm.ac.in)
        run: |
          echo "Last updated at $(date -u)" >> daily_status.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "22f3000940@ds.study.iitm.ac.in"
          git add daily_status.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push